### ISSUE TITLE
submit and launch buttons should be sprites

### ISSUE THREAD

**Issue by kevzettler** [cloudfuji/open_source_rails#11]
The images aren't preloaded and currently flash when loading the different states

**Comment by HashNuke** [comment]
Oh I just told bran to preload the images.
On 22 Jul 2011 00:18, "kevzettler" <
reply@reply.github.com>
wrote:

**Comment by kevzettler** [comment]
Thanks Akash, i'm just ticketing it out so we know the scope of work

**Comment by bryzettler** [comment]
Done
