### ISSUE TITLE
Form should retain data on failure

### ISSUE THREAD

**Issue by kevzettler** [cloudfuji/open_source_rails#13]
The submit form should keep the data the user entered and be populated if there submission fails so they don't have to reenter all the fields

**Comment by HashNuke** [comment]
Bryan, it's not displaying the values coz you are setting the :value option for the fields. Remove that option and Rails will automatically set the value for the fields. A way to display guide snippets for each field like "enter your awesome tagline here", would be to add it via javascript. If a field is empty onload, add it. If a field's on change ('change' event) value is empty, add it again. For the last case, just make sure you also check by getting the input and stripping the value to white spaces and then checking if the str length is zero. That way it'll be able to set the value to the guide snippet even if the value is a bunch of spaces.

**Comment by bryzettler** [comment]
Done
