### ISSUE TITLE
Project, icon - api

### ISSUE THREAD

**Issue by kevzettler** [cloudfuji/open_source_rails#16]
We want to share icons between bushi.do and osr.bushi.do. We are collecting icons at osr.bushi.do We need a method added to the projects controller that will respond with a requested projects icon.

Projects#icon

osr.bushi.do/projects/icon?repo=git@github.com/sssh

This controller action should look up a project by its source_url from the url repo parameter. And respond with the image file.

**Comment by HashNuke** [comment]
what's the "/sssh" part for?

**Comment by kevzettler** [comment]
its a bad example of a git url
