### ISSUE TITLE
add jquery validation engine to submission

### ISSUE THREAD

**Issue by kevzettler** [cloudfuji/open_source_rails#18]
Add inline validation to the submit form

http://www.position-absolute.com/articles/jquery-form-validator-because-form-validation-is-a-mess/

**Comment by HashNuke** [comment]
The app uses client_side_validations so we just need to pass :validate=>true to the form helper and it'll validate inline. Wee ned to style it using something else tho. Like you said, jquery validations looks good.

**Comment by bryzettler** [comment]
DONE
