### ISSUE TITLE
/admin crashes with latest rails

### ISSUE THREAD

**Issue by kevzettler** [cloudfuji/open_source_rails#19]
since the rails update i am getting this trying to access /admin

NameError in Admin/dashboard#index

Showing /Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/app/views/active_admin/dashboard/index.html.arb where line #1 raised:

undefined local variable or method `params' for #ActiveAdmin::Views::Pages::Dashboard:0x000001070dee88
Extracted source (around line #1):

1: render view_factory.dashboard_page
Rails.root: /Users/kevisazombie/Projects/Web/bushido_opensourcerails

Application Trace | Framework Trace | Full Trace
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/arbre/html.rb:20:in `method_missing'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/views/pages/base.rb:17:in`add_classes_to_body'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/views/pages/base.rb:8:in `build'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/arbre/html.rb:36:in`build_tag'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/arbre/html.rb:50:in `insert_tag'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/arbre/html.rb:14:in`method_missing'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/lib/active_admin/view_helpers/renderer_helper.rb:21:in `render'
/Users/kevisazombie/.rvm/gems/ruby-1.9.2-p180-patched@bushido_opensourcerails/bundler/gems/active_admin-4a6a8fe7f683/app/views/active_admin/dashboard/index.html.arb:1:in`___sers_kevisazombie__rvm_gems_ruby_______p____patched_bushido_opensourcerails_bundler_gems_active_admin__a_a_fe_f____app_views_active_admin_dashboard_index_html_arb__1722346494192069106_2206665520'
actionpack (3.1.0.rc5) lib/action_view/template.rb:144:in `block in render'
activesupport (3.1.0.rc5) lib/active_support/notifications.rb:57:in`instrument'
actionpack (3.1.0.rc5) lib/action_view/template.rb:142:in `render'

**Comment by HashNuke** [comment]
Checked. Same here. Bad activeadmin. I'll check by reverting to Rails rc4. I hope I can leave sprockets at rc12

**Comment by HashNuke** [comment]
Fixed!

Fixed by reverting back both Sprockets and Rails. Ironically, both the sprockets and rails update was to fix an asset serving error that had popped up after a recent rails commit (which got into rails rc5).
